version: '3'
services:
  app:
    build: .
    volumes:
    - .:/app
    links:
    - odoo
    environment:
      OOOR_URL: http://odoo:8069
      VERSION: 12.0
  db:
    image: postgres:11
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: odoo
      POSTGRES_USER: odoo
  odoo:
    image: odoo
    ports:
    - "8069:8069"
    links:
    - db
